### ISSUE TITLE
Compliance with TMDB API

### ISSUE THREAD

**Issue by Quikks1lver** [ContentWarnings/WebFrontend#6]
creating an issue to track this, for citations

general TMDB API use
> As per our terms of use, every application that uses our data or images is required to properly attribute TMDB as the source. Below you will find some logos you can use within your application. We've also included some basic brand guidelines.

streaming info
> Please note: In order to use this data you must attribute the source of the data as JustWatch. If we find any usage not complying with these terms we will revoke access to the API.

**Comment by nategaulke** [comment]
@Quikks1lver Do we have to use a logo for attributing TMDB? Otherwise this is done

**Comment by nategaulke** [comment]
@LightningStorms will add the TMDB Logo
